### ISSUE TITLE
Error while migrating a SQLite database

### ISSUE THREAD

**Issue by karmek-k** [WarsawLO/warsawlo-django#12]
**Steps to reproduce**
- Clone this repo
- Build the docker image:

```
$ docker build -t warsawlo .
```

- Create an `.env` file:

```
DJANGO_DEBUG=True
DJANGO_ALLOWED_HOSTS=*
DJANGO_SECRET_KEY=12345
```

- Run the container:

```
$ docker run --env-file .env warsawlo
```

**What happens?**
```
$ docker run --env-file .env warsawlo
Connection alive for > 0s
Connection alive for > 1s
Connection alive for > 2s
Connection alive for > 3s
Connection alive for > 4s
Connection alive for > 5s
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, search, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying search.0001_initial... OK
  Applying search.0002_contact_school_address_institutiondata_highschoolclass...Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 394, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "[]": syntax error



[rest omitted for brevity]
```

**Comment by mlazowik** [comment]
AFAIK we don't support sqlite. You can find an example `docker-compose.yml` here: https://github.com/WarsawLO/infra

**Comment by annkamsk** [comment]
We use postgresql, so the `SQL_ENGINE` env variable must be set to `django.db.backends.postgresql`. Added full build instructions to [README](https://github.com/WarsawLO/warsawlo-django#local-development).
